name: Any working branch

on:
  push:
    branches:
      - *

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Linting, Typechecking & Testing
        run: yarn ci

      - name: Build the app
        run: yarn build
